In [1]:
lax = (33.9, -118.4)

city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)

traveler_ids = [('USA', '311'), ('BRA', 'ce5'), ('ESP', 'xda')]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/ce5
ESP/xda
USA/311


In [2]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [3]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [4]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.9, (35.6, 139.7))
tokyo

City(name='Tokyo', country='JP', population=36.9, coordinates=(35.6, 139.7))

In [5]:
tokyo.population

36.9

In [6]:
tokyo[1]

'JP'

In [7]:
City._fields

('name', 'country', 'population', 'coordinates')

In [8]:
tokyo._asdict()

{'name': 'Tokyo',
 'country': 'JP',
 'population': 36.9,
 'coordinates': (35.6, 139.7)}

In [9]:
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [10]:
l[2:]

[30, 40, 50, 60]

In [11]:
s = 'bicycle'
s[::3]

'bye'

In [12]:
s[::-1]

'elcycib'

In [13]:
s[::-2]

'eccb'

In [14]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [16]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [17]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [20]:
l[2::5] = [100]
l

[0, 1, 100, 11, 5, 22, 9]

In [21]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [22]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [23]:
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [24]:
t

(1, 2, [30, 40, 50, 60])

In [25]:
fruits = ['grape', 'rasp', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'rasp']

In [26]:
fruits

['grape', 'rasp', 'apple', 'banana']

In [28]:
sorted(fruits, key=len)

['rasp', 'grape', 'apple', 'banana']

In [29]:
sorted(fruits, key=len, reverse=True)

['banana', 'grape', 'apple', 'rasp']

In [30]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'rasp']

In [31]:
import bisect
import sys

haystack = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
needles = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

row_fmt = '{0.2d} @ {1:2d}    {2}{0:<2d}'

def bemo(bisect_fn):
    for needle in reversed(needles):
        position = bisect_fn(haystack, needle)
        offset = position * '  |'
        print(row_fmt.format(needle, position, offset))

In [32]:
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.4945196426157449

In [33]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)

In [34]:
fp.close()

In [36]:
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()

In [37]:
floats2[-1]

0.4945196426157449

In [38]:
floats2 == floats

True

In [39]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
type(a)

numpy.ndarray

In [41]:
a.shape

(12,)

In [42]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a[2]

array([ 8,  9, 10, 11])

In [44]:
a[2, 1]

9

In [45]:
a[:, 1]

array([1, 5, 9])

In [46]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [47]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
dq.rotate(3)

In [49]:
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [50]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [51]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [53]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])